### ISSUE TITLE
Test code cannot access internal functions in same module

### ISSUE THREAD

**Issue by ansman** [google/dagger#2306]
While trying to upgrade to Dagger 2.31.2 I noticed that some of my tests failed to compile saying that the functions they were testing were not accessible because they are `internal`. After some experimentation I concluded that `enableExperimentalClasspathAggregation` was the culprit. If I enable it my tests fail to compile, if I leave it disabled they compile just fine.

I'm assuming this has something to do with how that is implemented and I'm guessing it tweaks `kapt` or something like that.

The module in question is an android library module and I'm using the following dagger/kapt options:
```kotlin
kapt {
  useBuildCache = true
  correctErrorTypes = true

  arguments {
    arg("dagger.fastInit", "enabled")
    arg("dagger.validateTransitiveComponentDependencies", "DISABLED")
  }
}

hilt {
  enableExperimentalClasspathAggregation = true
}

android {
  lintOptions.isCheckReleaseBuilds = false
}
```

**Comment by danysantiago** [comment]
Thanks for reporting this, it seems to be an issue with the local host unit test but not with android tests, I'll take a look.

**Comment by danysantiago** [comment]
@ansman, if you run your tests from the command line do they work (`./gradlew clean yourModule:testDebug`)? I think this issue is related to Android Studio using its own classpath and compile tasks for running host-side unit tests. This is something that is fixed in Android Studio 'Arctic Fox' (with AGP 7.x) which will use the same Gradle task and classpath as when tests are executed via Gradle invocations.

**Comment by ansman** [comment]
It does not work either AS or the command line.

**Comment by danysantiago** [comment]
Bummer, can you share with me the AS, AGP and Kotlin versions you are using? Thanks!

**Comment by ansman** [comment]
Sure, we're using AS 4.2 Beta 3, AGP 4.2.0-beta03 and Kotlin 1.4.21

**Comment by ansman** [comment]
@danysantiago I just tried building dagger from `master` and we still see the same issue.

**Comment by danysantiago** [comment]
Oh, oh! Did you built both Dagger & Hilt from `master`? The fix for this is suppose to be in the Hilt Gradle Plugin.

**Comment by ansman** [comment]
Yeah, I built all of it

**Comment by danysantiago** [comment]
Thanks for letting me know, I kept poking around and was able to reproduce the issue, will work on a fix.

**Comment by sergeys-opera** [comment]
I face the same issue with `enableExperimentalClasspathAggregation = true`. It also breaks `:app:lintRelease`:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintRelease'.
> Could not resolve all files for configuration ':app:debugUnitTestRuntimeClasspath'.
```

**Comment by danysantiago** [comment]
@ansman, merged a change that should fix this issue (this time for realz 😅 ) , if you could confirm it by either building from `master` or trying out the [snapshots](https://oss.sonatype.org/content/repositories/snapshots/com/google/dagger/) that would be amazing.

@sergeys-opera, the Lint issue seems something separate from the original problem described here, please file a new issue. If you can, please also try using AGP 7.0+ (its on alpha), we are aware of some problems with Lint in AGP 4.2 and 4.1.

**Comment by ansman** [comment]
I can confirm it's working using a snapshot build off master 👏
